import Head from "next/head";
import Product from "../components/Product";

export default function Home() {
  return (
    <div className="font-Play">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather&family=Play&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Product />
    </div>
  );
}
